GET http://localhost:5134/petStores

###

GET http://localhost:5134/Categories

###
GET http://localhost:5134/petStores/1

###
GET http://localhost:5134/petStores/2

###
GET http://localhost:5134/petStores/4
###

GET http://localhost:5134/petStores

###
POST  http://localhost:5134/petStores
Content-Type: application/json

{
    "PetName": "Zebra",
    "CategoryName": "Others",
    "gender": "Male",
    "petDescription": "Black and white horse, 40 years life plain",
    "price": 50000.01,
    "birthDay": "2021-08-08",
    "ImageUrl": "images/Others/zebra.jpg"
}


###
POST  http://localhost:5134/petStores
Content-Type: application/json

{
    "PetName": "BulBrishtish long hair",
    "CategoryName": "Cat",
    "gender": "Male",
    "petDescription": "Big",
    "price": 98.01,
    "birthDay": "2023-09-09",
    "ImageUrl": "images/Cat1.jpg"
}

###
POST  http://localhost:5134/petStores
Content-Type: application/json

{
    "PetName": "BulBrishtish long hair",
    "CategoryName": "Cat",
    "gender": "FemalMale",
    "petDescription": "Big",
    "price": 98.01,
    "birthDay": "2023-09-09",
    "ImageUrl": "images/Cat1.jpg"
}


###
POST  http://localhost:5134/petStores
Content-Type: application/json

{
    "PetName": "Adrienne Legault",
    "CategoryName": "Fish",
    "gender": "FemalMale",
    "petDescription": "Big",
    "price": 98.01,
    "birthDay": "2023-09-09",
    "ImageUrl": "images/Cat1.jpg"
}

###
POST  http://localhost:5134/petStores
Content-Type: application/json

{
    "PetName": "Parakeets",
    "CategoryName": "Bird",
    "gender": "FemalMale",
    "petDescription": "Big",
    "price": 98.01,
    "birthDay": "2023-09-09",
    "ImageUrl": "images/Parakeets.jpg"
}

###
POST  http://localhost:5134/petStores
Content-Type: application/json

{
    "PetName": "Spider",
    "CategoryName": "Insect",
    "gender": "FemalMale",
    "petDescription": "Big",
    "price": 98.01,
    "birthDay": "2023-09-09",
    "ImageUrl": "images/spider.jpg"
}





### wrong Type
POST  http://localhost:5134/petStores
Content-Type: application/json

{
    "itemId": "F-002 vvvv00000000v",
    "productId": "F-FM-002",
        "petType": "Fish",
    "gender": "Female",
    "petDescription": "Big",
    "price": 99998.01,
    "birthDay": "2023-09-09"
}

###
PUT  http://localhost:5134/petStores/5
Content-Type: application/json

{
    "PetName": "Fancy Guppies",
    "CategoryName": "Cat",
    "gender": "Female",
    "petDescription": "Red",
    "price": 9.01,
    "birthDay": "2023-11-09",
    "ImageUrl": "images/Fish/Fancy Guppies.jpg"
}

###
DELETE   http://localhost:5134/petStores/1

###
DELETE   http://localhost:5134/petStores/211

###
DELETE   http://localhost:5134/petStores/3


### wrong Type
POST  http://localhost:5134/registration
Content-Type: application/json

{
    "Username": "Khoa Pham Customer" , 
     "Password": "1234567890", 
     "FullName": "Khoa Pham Customer", 
     "Email": "khoapham.1234567@gmail.com", 
     "Address": "121, 3/2 Street, District 10, HCM City",
     "Role": "Customer"
}


### wrong Type
PUT  http://localhost:5134/registration/1
Content-Type: application/json

{
    "Username": "Khoa Pham Customer" , 
     "Password": "1234567890", 
     "FullName": "Khoa Pham Customer", 
     "Email": "khoapham.1234567@gmail.com", 
     "Address": "121, 3/2 Street, District 10, HCM City",
     "Role": "Customer"
}